server:
  port: 9999
  servlet:
    context-path: /dbExport
spring:
  application:
    name: db-export
  thymeleaf:
    cache: false
    charset: UTF-8
    template-loader-path: classpath:/templates/
    prefix: classpath:/templates/thymeleaf/
    suffix: .html
    mode: HTML5
    encoding: UTF-8

word:
  model:
    #生成的文档的路径
    export: D://
    #生成文档的名称
    file-name: export.docx
    #此处win为打包后的路径
    #import: package/resources/docx/import.docx
    #sub-model: package/resources/docx/sub_model.docx
    #此处linux为打包后的路径
    #import: ../resources/docx/import.docx
    #sub-model: ../resources/docx/sub_model.docx
    #此处为从IDE启动的配置
    import: docx/import.docx
    sub-model: docx/sub_model.docx