server:
  port: 9999
  servlet:
    context-path: /

spring:
  application:
    name: db-export
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  web:
    resources:
      static-locations: classpath:/static/

database:
  # 数据库连接池框架 默认druid 可选hikaricp,druid
  pool: druid
  jdbc:
    mysql: jdbc:mysql://%s:%s/%s?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useSSL=false
    oracle: jdbc:oracle:thin:@//%s:%s/%s
    sqlServer: jdbc:sqlserver://%s:%s;databaseName=%s
    postgresql: jdbc:postgresql://%s:%s/%s
    clickhouse: jdbc:clickhouse://%s:%s/%s
    sqlite: jdbc:sqlite:%s
    dm: jdbc:dm://%s:%s/%s
  driver:
    mysql: com.mysql.cj.jdbc.Driver
    oracle: oracle.jdbc.OracleDriver
    sqlServer: com.microsoft.sqlserver.jdbc.SQLServerDriver
    postgresql: org.postgresql.Driver
    clickhouse: com.clickhouse.jdbc.ClickHouseDriver
    sqlite: org.sqlite.JDBC,
    dm: dm.jdbc.driver.DmDriver