server:
  port: 9999
  servlet:
    context-path: /dbExport
spring:
  application:
    name: db-export
  thymeleaf:
    cache: false
    charset: UTF-8
    prefix: classpath:/templates/thymeleaf/
    suffix: .html
    mode: HTML
    encoding: UTF-8
export:
  template-copy-path: .databaseExport

database:
  jdbc:
    mysql: jdbc:mysql://%s:%s/%s?serverTimezone=UTC
    oracle: jdbc:oracle:thin:@//%s:%s/%s
    sqlServer: jdbc:sqlserver://%s:%s;databaseName=%s
  driver:
    mysql: com.mysql.cj.jdbc.Driver
    oracle: oracle.jdbc.driver.OracleDriver
    sqlServer: com.microsoft.sqlserver.jdbc.SQLServerDriver
  getTableNameSql:
    mysql: select table_name TABLE_NAME, table_comment COMMENTS from information_schema.tables where table_schema='%s' and table_type='base table'
    oracle: select t1.TABLE_NAME,t2.COMMENTS from user_tables t1 ,user_tab_comments t2 where t1.table_name = t2.table_name(+)
    sqlServer: select TABLE_NAME=d.name,COMMENTS=f.value  from sysobjects d left join sys.extended_properties f on d.id=f.major_id and f.minor_id=0 where d.xtype = 'u' and d.name != 'sysdiagrams'
  getColumnNameInfoSql:
    mysql: select column_name COLUMN_NAME,column_default DATA_DEFAULT,is_nullable NULLABLE,data_type DATA_TYPE,character_maximum_length DATA_LENGTH,column_comment COMMENTS, COLUMN_TYPE COLUMN_TYPE,EXTRA EXTRA_INFO,COLUMN_KEY COLUMN_KEY from information_schema.columns where table_name = '%s' and table_schema = (select database()) order by ordinal_position
    oracle: select t1.COLUMN_NAME,t1.DATA_TYPE,case when t1.DATA_TYPE = 'NUMBER' then case when t1.DATA_PRECISION is null then t1.DATA_LENGTH else t1.DATA_PRECISION end else t1.CHAR_LENGTH end as "DATA_LENGTH",t1.NULLABLE,t1.DATA_DEFAULT,t2.COMMENTS from user_tab_cols t1, user_col_comments t2 where t1.table_name = '%s' and t1.TABLE_NAME = t2.table_name and t1.COLUMN_NAME = t2.column_name(+)
    sqlServer: select  COLUMN_NAME = a.name ,DATA_TYPE = b.name,DATA_LENGTH = columnproperty(a.id, a.name, 'PRECISION') , NULLABLE = case when a.isnullable = 1 then 'âˆš' else '' end , DATA_DEFAULT = isnull(e.text, ''),COMMENTS = isnull(g.[value], '') from syscolumns a left join systypes b on a.xusertype = b.xusertype inner join sysobjects d on a.id = d.id and d.xtype = 'U' and d.name <> 'dtproperties' left join syscomments e on a.cdefault = e.id left join sys.extended_properties g on a.id = g.major_id and a.colid = g.minor_id left join sys.extended_properties f on d.id = f.major_id and f.minor_id = 0 where d.name = '%s'